#!/usr/bin/env python3
"""Build the avatar set: copy each character's original sprite as <slug>.png and
make three alternate-costume palettes (<slug>-p2/-p3/-p4.png) by rotating the hue
of the saturated pixels while keeping outlines, whites and greys. Then write
public/data/avatars.js from scripts/roster.json and a review contact sheet.

Usage: python3 scripts/make-avatar-palettes.py   (run from game/)
Overrides: add {"slug": {"p2": hueDegrees, ...}} to OVERRIDES below for hand-picked shifts.
"""
import json, os, sys, colorsys
from PIL import Image, ImageDraw

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
RAW = os.path.join(ROOT, "public/assets/avatars/raw")
OUT = os.path.join(ROOT, "public/assets/avatars")
ROSTER = json.load(open(os.path.join(ROOT, "scripts/roster.json")))

SHIFTS = {"p2": 120, "p3": 240, "p4": 60}
OVERRIDES = {
    # Ghosts: keep them clearly different from each other and from Inky (cyan).
    "blinky": {"p2": 150, "p3": 280, "p4": 45},
    "pinky": {"p2": 100, "p3": 200, "p4": 300},
    "clyde": {"p2": 90, "p3": 200, "p4": 300},
    "ghost": {"p2": 150, "p3": 280, "p4": 330},
}
SAT_MIN, VAL_MIN = 0.22, 0.18

def shift_hue(img, deg):
    im = img.convert("RGBA")
    px = im.load()
    w, h = im.size
    for y in range(h):
        for x in range(w):
            r, g, b, a = px[x, y]
            if a == 0:
                continue
            hh, s, v = colorsys.rgb_to_hsv(r / 255, g / 255, b / 255)
            if s < SAT_MIN or v < VAL_MIN:
                continue
            hh = (hh + deg / 360.0) % 1.0
            r2, g2, b2 = colorsys.hsv_to_rgb(hh, s, v)
            px[x, y] = (int(r2 * 255 + .5), int(g2 * 255 + .5), int(b2 * 255 + .5), a)
    return im

TINTS = {"p2": 130, "p3": 320, "p4": 200}  # green, pink, blue tints for low-colour sprites

def saturated_fraction(img):
    px = img.load(); w, h = img.size; n = sat = 0
    for y in range(h):
        for x in range(w):
            r, g, b, a = px[x, y]
            if a == 0: continue
            n += 1
            hh, s_, v = colorsys.rgb_to_hsv(r / 255, g / 255, b / 255)
            if s_ >= SAT_MIN and v >= VAL_MIN: sat += 1
    return sat / max(1, n)

def tint_light(img, deg):
    """For black-and-white sprites: colour the light pixels instead of rotating hue."""
    im = img.convert("RGBA"); px = im.load(); w, h = im.size
    for y in range(h):
        for x in range(w):
            r, g, b, a = px[x, y]
            if a == 0: continue
            hh, s_, v = colorsys.rgb_to_hsv(r / 255, g / 255, b / 255)
            if v < 0.45: continue
            r2, g2, b2 = colorsys.hsv_to_rgb(deg / 360.0, 0.5 if s_ < SAT_MIN else s_, v)
            px[x, y] = (int(r2 * 255 + .5), int(g2 * 255 + .5), int(b2 * 255 + .5), a)
    return im

def source_for(slug):
    raw = os.path.join(RAW, slug + ".png")
    orig = os.path.join(OUT, slug + ".png")
    if os.path.exists(raw):
        return raw
    if os.path.exists(orig):
        return orig
    return None

made = []
for slug, name, franchise, move in ROSTER:
    src = source_for(slug)
    if not src:
        print("MISSING", slug, file=sys.stderr)
        continue
    im = Image.open(src).convert("RGBA")
    bb = im.getbbox()
    if bb:
        im = im.crop(bb)
    im.save(os.path.join(OUT, slug + ".png"))
    low_colour = saturated_fraction(im) < 0.2
    for p, deg in SHIFTS.items():
        d = OVERRIDES.get(slug, {}).get(p, deg)
        out = tint_light(im, TINTS[p]) if low_colour else shift_hue(im, d)
        out.save(os.path.join(OUT, f"{slug}-{p}.png"))
    if low_colour: print("tint mode:", slug)
    made.append((slug, name, franchise, move, im.size))

# Roster module.
lines = ["// GENERATED by scripts/make-avatar-palettes.py from scripts/roster.json. Edit those, not this.",
         "// Each character ships in four palettes: p1 is the original sprite, p2-p4 are",
         "// alternate costume colours. Server and client both import this file.",
         'export const PALETTES = ["p1", "p2", "p3", "p4"];', "",
         "// move: thunderbolt | slash | spin | kirby | jump", "export const ROSTER = ["]
for slug, name, franchise, move, size in made:
    lines.append(f'  {{ c: {json.dumps(slug)}, name: {json.dumps(name)}, franchise: {json.dumps(franchise)}, move: {json.dumps(move)}, w: {size[0]}, h: {size[1]} }},')
lines.append("];")
lines.append("""
export const ROSTER_BY_ID = Object.fromEntries(ROSTER.map((r) => [r.c, r]));

export function avatarFile(avatar) {
  if (!avatar) return "";
  const suffix = avatar.p && avatar.p !== "p1" ? "-" + avatar.p : "";
  return "assets/avatars/" + avatar.c + suffix + ".png";
}

export function avatarName(avatar) {
  const r = avatar && ROSTER_BY_ID[avatar.c];
  return r ? r.name : "?";
}

export function franchises() {
  const out = [];
  for (const r of ROSTER) if (!out.includes(r.franchise)) out.push(r.franchise);
  return out;
}
""")
open(os.path.join(ROOT, "public/data/avatars.js"), "w").write("\n".join(lines))

# Review sheet: one row per character, four palettes.
cols, cw, ch = 4, 90, 100
per_col = 23
groups = [made[i:i + per_col] for i in range(0, len(made), per_col)]
sheet = Image.new("RGBA", (len(groups) * (cols * cw + 150), per_col * ch), (63, 68, 58, 255))
d = ImageDraw.Draw(sheet)
for gi, grp in enumerate(groups):
    ox = gi * (cols * cw + 150)
    for ri, (slug, name, franchise, move, size) in enumerate(grp):
        d.text((ox + 4, ri * ch + 40), slug[:16], fill=(236, 220, 192, 255))
        for pi, p in enumerate(["p1", "p2", "p3", "p4"]):
            f = os.path.join(OUT, slug + ("" if p == "p1" else "-" + p) + ".png")
            im = Image.open(f).convert("RGBA")
            scale = max(1, min(5, 80 // max(1, im.height)))
            im2 = im.resize((im.width * scale, im.height * scale), Image.NEAREST)
            x = ox + 150 + pi * cw + (cw - im2.width) // 2
            y = ri * ch + 8 + (80 - im2.height)
            sheet.paste(im2, (x, y), im2)
sheet_path = os.path.join(ROOT, "docs/avatar-palettes.png")
sheet.save(sheet_path)
print(f"{len(made)} characters x 4 palettes -> {OUT}; roster -> public/data/avatars.js; review sheet -> docs/avatar-palettes.png")
